import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css";
import { TRPCProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ThemeProvider";
import PopunderAd from "@/components/PopunderAd";
import PushNotificationAd from "@/components/PushNotificationAd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Tube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <ClerkProvider>
        <html lang="en">
          <body
            className={inter.className}>
            <TRPCProvider>
              <Toaster />
              <PopunderAd />
              <PushNotificationAd />
              {children}
            </TRPCProvider>
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
